DEFAULT_CONFIG = {
    "agent_llm_model": "mimo-v2.5-pro",
    "graph_llm_model": "mimo-v2.5-pro",
    "vision_llm_model": "mimo-v2.5-pro",
    "agent_llm_provider": "mimo",
    "graph_llm_provider": "mimo",
    "vision_llm_provider": "mimo",
    "agent_llm_temperature": 0.1,
    "graph_llm_temperature": 0.1,
    "vision_llm_temperature": 0.1,
    "api_key": "",
    "anthropic_api_key": "",
    "qwen_api_key": "",
    "siliconflow_api_key": "",
    "mimo_api_key": "",
    "qwen_base_url": "https://token-plan-cn.xiaomimimo.com/v1",
    "qwen_api_env_name": "MIMO_API_KEY",
    "use_multimodal_images": False,
}
