DEFAULT_CONFIG = {
    "agent_llm_model": "mimo-v2.5-pro",
    "graph_llm_model": "mimo-v2.5-pro",
    "vision_llm_model": "mimo-v2.5-pro",
    "agent_llm_provider": "qwen",
    "graph_llm_provider": "qwen",
    "vision_llm_provider": "qwen",
    "agent_llm_temperature": 0.1,
    "graph_llm_temperature": 0.1,
    "vision_llm_temperature": 0.1,
    "api_key": "",
    "anthropic_api_key": "",
    "qwen_api_key": "",
    "mimo_api_key": "",
    "siliconflow_api_key": "",
    "qwen_base_url": "",
    "qwen_api_env_name": "",
    "use_multimodal_images": True,
}
